name: GoDex Website update

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Node install & build
    - name: Node install & build
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        port: 21
        local-dir: "build/"
        server-dir: "pgo/"
