name: GoDex Manual Pokédex update
on: 
  workflow_dispatch:
    inputs:
      pokemonNumber:
        description: 'Pokémon number to add to Pokédex'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Updating pokemon.json with newly caught pokémons
        run: |
          jq "(.caught += [${{ github.event.inputs.pokemonNumber }}] | .caught |= sort)" ./public/pokedex/pokemons.json > ./public/pokedex/pokemons2.json
          mv ./public/pokedex/pokemons2.json ./public/pokedex/pokemons.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: '[Semi-auto PR] Updated caught pokédex'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: pr-updates
          delete-branch: true
          title: '[Semi-auto PR] Updated caught pokédex'
          body: |
            [Semi-auto PR] Updated caught pokédex
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
